server:
  port: 3010

nacos:
  ip: @nacos.ip@
  port: @nacos.port@
  namespace: @nacos.namespace@
  username: @nacos.username@
  password: @nacos.password@

#配置日志地址
logging:
  file:
    path: @logging.file.path@
    name: @logging.file.path@/${spring.application.name}/${spring.application.name}-info.log
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        namespace: ${nacos.namespace}
        server-addr: ${NACOS_HOST:${nacos.ip}}:${NACOS_PORT:${nacos.port}}
      config:
        namespace: ${nacos.namespace}
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:application-@spring.profiles.active@.yml
      - nacos:${spring.application.name}-@spring.profiles.active@.yml
  profiles:
    active: @spring.profiles.active@

application:
  version: @revision@





